server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    min-spare-threads: 30
  port: 8080
  servlet:
    context-path: /emos-wx-api
spring:
  application:
    name: emos-wx-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.26.216.237:13206/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: feb14766ddf13364
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
    mongodb:
      host: 120.26.216.237
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abcd123456
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: 951219568@aliyun.com
    password: zxy123456789!
  redis:
    database: 0
    host: 120.26.216.237
    port: 6379
    password: zxy123456789
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
# mybatis日志
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxy.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  root:
    level: info
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"
#配置秘钥
emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
